FROM nginxinc/nginx-unprivileged:stable-alpine@sha256:adf5042a17f4ecdd200c595fa9ffd1be37efb18f89a830bd1a00e4ab4d59d42c
COPY strobo.html /usr/share/nginx/html/index.html
COPY LICENSE /usr/share/nginx/html/LICENSE
USER 101:101
EXPOSE 8080
